/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rov.bridge;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author rashad
 *
 *
 */
public class BT extends javax.swing.JFrame {

    static int newH, newW;
    static Thread thread;

    /**
     * Creates new form BT
     */
    public BT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Current Direction : ");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Current Arm Action :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Current Rotation :");

        jLabel4.setText("Not Moving");

        jLabel5.setText("Not Rotation");

        jLabel6.setText("Arm is Stopped");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Current Speed  : ");

        jLabel8.setText("0 PWM");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Connected to :  ");

        jLabel10.setText("PHONE MODEL");

        jTextField1.setText("Add IP Address");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD IP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Current Temprature :");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setText("Current Pressure : ");

        jLabel14.setText("0");

        jLabel15.setText("0");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setText("Current Action :");

        jLabel17.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (!thread.isAlive()) {
            thread.start();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     *
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            BT H = new BT();
            H.setVisible(true);
            H.setTitle("BT MODE");

            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            newW = dim.width / 2 - H.getSize().width / 2;
            newH = dim.height / 2 - H.getSize().height / 2;
            H.setLocation(newW, newH);

        });

        thread = new Thread() {

            @Override
            public void run() {

                System.out.println("Thread Running");

                try {

                    Communication.recieve();

                } catch (IOException ex) {

                    Logger.getLogger(USB.class.getName()).log(Level.SEVERE, null, ex);

                }

                //Executes the method while passing the IP to it to connect via bluetooth/wifi
                IP = jTextField1.getText();
                adbControl(IP);

            }
        };

    }

    /**
     * ADB and Stuff
     */
    private static void adbControl(String str) {

        System.out.println("Running ADB..");

        line = "";

        try {

            process2 = Runtime.getRuntime().exec("/home/rashad/Documents/Workspace/Android-IDE/Android-Eclipse/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s " + str + ":5555" + " shell getprop " + "ro.product.model");
            br2 = new BufferedReader(new InputStreamReader(process2.getInputStream()));

            if ((line2 = br2.readLine()) != null) {

                System.out.println("Connected to : " + line2);
                jLabel10.setText(line2);

            }

            process = Runtime.getRuntime().exec("/home/rashad/Documents/Workspace/Android-IDE/Android-Eclipse/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s " + str + ":5555" + " logcat -s " + "ROV");
            br = new BufferedReader(new InputStreamReader(process.getInputStream()));

            while (true) {

                jLabel17.setText("Iniatilzing..");

                try {

                    jLabel17.setText("Getting Commands..");

                    while ((line = br.readLine()) != null) {

                        if (line.contains("open1")) {

                            System.out.println("open1");

                            Communication.send("o");

                            jLabel6.setText("Opening");

                        }

                        if (line.contains("open0")) {

                            System.out.println("open0");
                            Communication.send("oo");
                            jLabel6.setText("Nothing");
                        }

                        if (line.contains("close1")) {

                            System.out.println("close1");
                            Communication.send("c");
                            jLabel6.setText("Closing");

                        }

                        if (line.contains("close0")) {

                            System.out.println("close0");
                            Communication.send("cc");

                            jLabel6.setText("Nothing");

                        }

                        if (line.contains("up1")) {

                            System.out.println("up1");
                            Communication.send("u");
                            jLabel4.setText("Up");
                        }

                        if (line.contains("up0")) {

                            System.out.println("up0");
                            Communication.send("uu");
                            jLabel4.setText("Nothing");

                        }

                        if (line.contains("down1")) {

                            jLabel4.setText("Down");
                            Communication.send("d");
                            System.out.println("down1");

                        }

                        if (line.contains("down0")) {

                            jLabel4.setText("Nothing");
                            Communication.send("dd");
                            System.out.println("down0");

                        }

                        if (line.contains("left1")) {

                            jLabel5.setText("Left");
                            Communication.send("l");
                            System.out.println("left1");

                        }

                        if (line.contains("left0")) {

                            jLabel5.setText("Nothing");
                            Communication.send("ll");
                            System.out.println("left0");

                        }

                        if (line.contains("right1")) {

                            jLabel5.setText("Right");
                            Communication.send("r");
                            System.out.println("right1");

                        }

                        if (line.contains("right0")) {

                            jLabel5.setText("Nothing");
                            Communication.send("rr");
                            System.out.println("right0");

                        }

                        if (line.contains("armu1")) {
                            jLabel6.setText("Up");
                            Communication.send("au");
                            System.out.println("armu1");

                        }

                        if (line.contains("armu0")) {

                            jLabel6.setText("Nothing");
                            Communication.send("auu");
                            System.out.println("armu0");

                        }

                        if (line.contains("arml1")) {
                            jLabel6.setText("Left");
                            Communication.send("al");

                            System.out.println("arml1");
                        }

                        if (line.contains("arml0")) {

                            jLabel6.setText("Nothing");
                            Communication.send("all");
                            System.out.println("arml0");

                        }

                        if (line.contains("armd1")) {

                            jLabel6.setText("Down");
                            Communication.send("ad");

                            System.out.println("armd1");
                        }

                        if (line.contains("armd0")) {

                            jLabel6.setText("Nothing");
                            Communication.send("add");
                            System.out.println("armd0");

                        }

                        if (line.contains("armr1")) {
                            jLabel6.setText("Right");
                            Communication.send("ar");
                            System.out.println("armr1");
                        }

                        if (line.contains("armr0")) {

                            jLabel6.setText("Nothing");
                            Communication.send("arr");
                            System.out.println("armr0");
                        }

                        if (line.contains("pressure")) {

                            jLabel15.setText("getting pressure..");
                            Communication.send("m");
                            System.out.println("getting pressure..");

                        }

                        if (line.contains("temprature")) {

                            jLabel14.setText("getting temprature..");
                            Communication.send("t");
                            System.out.println("getting temprature..");

                        }

                        if (line.contains("for")) {

                            jLabel4.setText("forward");
                            Communication.send("f");
                            System.out.println("for");

                        }

                        if (line.contains("back")) {

                            jLabel4.setText("backward");
                            Communication.send("b");
                            System.out.println("back");

                        }

                        if (line.contains("Speed")) {

                            p = Pattern.compile("-?\\d+");
                            m = p.matcher(line);

                            int i = 3;

                            //doing this to extract speed from the adb lines
                            //it comes in 3 stages so we get only the  even line
                            //it gets the right line
                            while (m.find()) {

                                if (i % 2 == 0) {

                                    System.out.println(m.group());
                                    jLabel8.setText(m.group() + " PWM");
                                    Communication.send("s" + m.group());

                                    if (m.group().equals("0")) {

                                        jLabel4.setText("Nothing");

                                    }

                                }

                                i++;

                            }

                        }

                    }

                } catch (IOException | NullPointerException ex) {

                    Logger.getLogger(USB.class.getName()).log(Level.SEVERE, null, ex);

                }

            }

        } catch (IOException ex) {

            System.out.println("Running ADB Failed!! .. " + ex);

        }
    }
    // Variables declaration - eshta modify             
    static Process process, process2, process3;
    static String line, line2;
    static BufferedReader br, br2;
    static Pattern p;
    static Matcher m;
    static String IP;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
